### PR TITLE
[BB-08]: big brain app fetch sushi api

### PR DESCRIPTION
**Pull request by PhantHive**
YouTrack: [BB-08](https://irisrobotics.youtrack.cloud/issue/PMI-44) 

Big Brain now fetch the Nest API to post request.
+ moved preventDefault at the beginning to avoid refresh

### CODE REVIEW

**Comment by PhantHive** [comment]
On my side this PR is ready for review:

- Sushi connection to Prod server
- Result prompted on the website

Next step will be on API side: ressource from json. I will be using already existing discord bot implementation.

**Comment by PyyLog** [comment]
I'm not sure what should be the result at the end ... I sent a text ans after few minutes, I got something I find really strange ...

image

The JSON object seems really strange to my eyes ... Maybe is it normal at your developping stage ? 

I also checked the server with given information in the .env, it's written "Hello World !". When, I'm sending a text, nothing happens on this side either. Is it supposed to show a JSON object or is this behaviour normal ?

**Comment by PhantHive** [comment]
yep @PyyLog  it is the normal behavior.
The purpose of this PR is just to establish a connection between the website, the API and the AI running on Gradio.
As said previously, the next step is: "Next step will be on API side: ressource from json. I will be using already existing discord bot implementation." which means to get ressources from JSON.

PS: JSON format is the format returned from the AI which is stringify causing the `\"`

About the process time:
We are running on a around 15 Gb fine-tuned large language model, which uses a T4 medium GPU  with only 16GB Vram which is barely enough to run a model efficiently. Also the actual implementation of the model runs on fp16 (float 16) which is quite low already. The model used as you know is Llama 2 7b which is a 7bilions parameters.

The model generate answer in about 30 seconds. We already have discussed the time-process issue with the referent teacher, as you remember. At this stage of developement, I have no way to make the global process faster.

Note: another PR will be open for the result type (will not be a json obviously) and another PR to improve the model (which is on a different repo: momo).

PS: To explain a bit more how gradio works:
Gradio is a space where you can run inference with your AI model using their GPU. Computation fees are calculated every minute, to avoid spending a lot of money during tests, the space will go into "sleep mode" every 5 minutes of inactivity. It will cause first call to be quite long as after a sleep, the space have to build again (which takes more than 2 minutes).

**Comment by PyyLog** [comment]
Oh! I see ... I forgot about the time of generation, but now I remember 🙂
If everything's normal, then it's ok for me.

**Comment by PhantHive** [comment]
ok, we have to discuss it together again when we have some time before Friday 1, because I see no ways to improve this process time at the moment.

**Review by PyyLog — APPROVED** [review]

**Pull request merged**
