### PR TITLE
[BB-04]: Handling data from SUSHI to render PDFs

### PR DESCRIPTION
**Pull request by PhantHive**
YouTrack: [PMI-61](https://irisrobotics.youtrack.cloud/issue/PMI-61) 
Linked PR: [SUSHI-05](https://github.com/ipsa-scrypt/sushi/pull/7)

**Context**
SUSHI is now sending pdfs to a base64 format.
This PR should handle the data conversion.

### CODE REVIEW

**Comment by PhantHive** [comment]
Capture d'écran 2023-12-04 001654

This is the current state of the PR.
We can successfully download the pdf retrieved by SUSHI thanks to Big Brain AI.

I am gonna make some code cleaning, better error handling etc.

**Comment by PhantHive** [comment]
Same as for SUSHI last PR (05), I would like to close this PR as it is doing what's it's suppose to do. 
I will open a PR to improve the deploy process and make sure everything is rollin' out.

**Comment by PhantHive** [comment]
@PyyLog ready for your review! 🌞

**Review by PyyLog — APPROVED** [review]
All clear for me, you can proceed.

**Pull request merged**
