### PR TITLE
[BB-09] Integration of downloadable links to the website render + Bonus

### PR DESCRIPTION
**Pull request by PyyLog**
YouTrack: [BB-09](https://irisrobotics.youtrack.cloud/issue/PMI-41) 

Integration for the output div is alsmost done. I have to verify with some use cases to see if all works well. 
Bonus: history of the conversation not finished yet because there is a bug in the display.

### CODE REVIEW

**Comment by PyyLog** [comment]
image

As you can see on this screenshot, when we return 2 resources, the display isn't great (both in the output and the history). I'm on it to debug the problem.

**Comment by PyyLog** [comment]
The problem is fixed 😉.
I also created a TS file for the demo purpose where we can add as many links as we like (to be displayed on the website), so that we won't have to juggle between several files to change them.

**Comment by PyyLog** [comment]
The problem is fixed 😉.
I also created a TS file for the demo purpose where we can add as many links as we like (to be displayed on the website), so that we won't have to juggle between several files to change them.

image

**Review by PhantHive — APPROVED** [review]
This definitely breaks the responsive but, it's working.
I guess we can merge :)

**Comment by PhantHive** [comment]
Just in case @PyyLog you are not making any other changes ?

**Comment by PyyLog** [comment]
For this PR, no anymore.

**Pull request merged**
